// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhnlxqxjxitpjlqvvvsq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhobmx4cXhqeGl0cGpscXZ2dnNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNTE1MjAsImV4cCI6MjA3MzYyNzUyMH0.Ep_7G8zd_gnBBYKIMpyBKSbo1uUB9antI9ertWuG4Xw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});